<?php

declare(strict_types=1);

define('RECOVERY_MODE_SELECTION', 0);
define('RECOVERY_MODE_ACP_REPAIR', 1);
define('RECOVERY_MODE_PLUGIN_UNINSTALL', 2);
define('RECOVERY_MODE_USER_MANAGEMENT', 3);
define('RECOVERY_MODE_CACHE_CLEAR', 4);
define('RECOVERY_MODE_PACKAGE_LIST_REPAIR', 5);
define('RECOVERY_MODE_PACKAGE_FILE_REPAIR', 6);
define('RECOVERY_MODE_RECOVERY_WIZARD', 7);
define('RECOVERY_MODE_SYSTEM_CHECK', 8);
define('RECOVERY_MODE_BACKUP_GUIDE', 9);
define('RECOVERY_MODE_DIRECTORY_STRUCTURE', 10);

define('RECOVERY_ENABLE_DEBUG', false);
define('RECOVERY_PACKAGE_ID_MAX_LEN', 191);
define('RECOVERY_PACKAGE_ID_PATTERN', '/^[a-zA-Z0-9._-]+$/');
define('RECOVERY_MAX_UPLOAD_BYTES', 104857600);
